name: Youtube Downloader
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt;
    - name: Set Environement Variable
      run: |
        export FLASK_APP=main.py
        export FLASK_DEBUG=1
        export FLASK_ENV=production
    - name: Run main.py
      run: |
        flask run